# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: siwonlee <tldnjs0821222@naver.com>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/24 19:51:43 by siwonlee          #+#    #+#              #
#    Updated: 2023/01/24 19:58:02 by siwonlee         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

all : $(NAME)

$(NAME) :
	gcc -Wall -Wextra -Werror -o $(NAME) ft_cat.c

clean :
	rm -f *.o

fclean : clean
	rm -f $(NAME)

re : fclean all
